/*
Copyright (c) 2013 - 2014, Nathan Muruganantha. All rights reserved.
*/

#ifndef _DERIVATIVE_ZEROCOUPONBONDVALUE_H_
#define _DERIVATIVE_ZEROCOUPONBONDVALUE_H_

#include <string>
#include <memory>
#include <atomic>
#include <mutex>

#include "IMake.hpp"
#include "SpinLock.hpp"
#include "IIRDataSrc.hpp"
#include "Name.hpp"
#include "IZeroCouponBondValue.hpp"

namespace derivative
{
	/// Class ZeroCouponBondValue represents current value of a zeroCouponBond
	/// It is constructed as a Named type. That is, only only one
	/// shared object per zeroCouponBond would be shared among all client(s)
	/// threads. Callers will have the ability to refresh from external source.
	class ZeroCouponBondValue : virtual public IZeroCouponBondValue,
		virtual public IMake,
		virtual public IIRDataSrc
	{

	public:

		enum {TYPEID = CLASS_ZEROCOUPONBONDVALUE_TYPE};

		/// Constructor with Exemplar for the Creator ZeroCouponBond value object
		ZeroCouponBondValue (const Exemplar &ex);

		/// construct ZeroCouponBondValue from a given Name
		/// used in IMake::Make(..)
		/// The object ID would be the same as that of underlying zeroCouponBond.
		ZeroCouponBondValue (const Name& nm);

		virtual ~ZeroCouponBondValue()
		{}

		shared_ptr<IMake> Make (const Name &nm);

		shared_ptr<IMake> Make (const Name &nm, const deque<boost::any>& agrs);

		/// construct ZeroCouponBondValue from input stream.		
		virtual void convert( istringstream  &input);

		const Name& GetName()
		{
			std::lock_guard<SpinLock> lock(m_lock);
			return m_name;
		}

		virtual double GetTradePrice() const
		{
			return m_tradePrice;
		}

		virtual double GetQuotedPrice() const
		{
			return m_quotedPrice;
		}

		/// returns the trade date when the price is reported
		virtual dd::date GetTradeDate() const
		{
			std::lock_guard<SpinLock> lock(m_lock);
			return m_tradeDate;
		}

		/// return the yield
		virtual double GetYield() const
		{
			return m_yield;
		}

		/// The maturity date of the bond
		virtual dd::date GetMaturityDate() const
		{
			std::lock_guard<SpinLock> lock(m_lock);
			return m_maturityDate;
		}

		virtual double GetDivYield() const
		{
			throw std::logic_error("Invalid call");
		}

		virtual dd::date GetProcessedDate() const 
		{
			std::lock_guard<SpinLock> lock(m_lock);
			return m_processedDate;
		}

		/// The processed date of the bond
		virtual void  SetProcessedDate(const dd::date& pDate)
		{
			std::lock_guard<SpinLock> lock(m_lock);
			m_processedDate = pDate;
		}

		virtual void SetTradePrice(double price)
		{
			m_tradePrice = price;
		}

		virtual void SetQuotedPrice(double price)
		{
			m_quotedPrice = price;
		}

		virtual std::shared_ptr<IAsset> GetAsset() const
		{
			std::lock_guard<SpinLock> lock(m_lock);
			return m_bond;
		}

		/// return bond.
		shared_ptr<const IZeroCouponBond> GetBond() const
		{
			std::lock_guard<SpinLock> lock(m_lock);
			return m_bond;
		}

		/// return cash flow generated by this bond
		virtual std::shared_ptr<cashFlowSetType> getCashFlowMap() const
		{
			std::lock_guard<SpinLock> lock(m_lock);
			return m_cashFlow;
		}

		/// Set the trade date when the price is reported
		virtual  void SetTradeDate(const dd::date& date)
		{
			std::lock_guard<SpinLock> lock(m_lock);
			m_tradeDate = date;
		}

		/// Set the div yield
		virtual void SetYield(double yield)
		{
			m_yield = yield;
		}

		/// The maturity date of the bond
		virtual void  SetMaturityDate(const dd::date& matDate)
		{
			std::lock_guard<SpinLock> lock(m_lock);
			m_maturityDate = matDate;
		}

		virtual std::shared_ptr<IZeroCouponBond> GetZeroCouponBond() const
		{
			std::lock_guard<SpinLock> lock(m_lock);
			return m_bond;
		}

		virtual void SetZeroCouponBond(std::shared_ptr<IZeroCouponBond> bond)
		{
			std::lock_guard<SpinLock> lock(m_lock);
			m_bond = bond;
		}

		virtual void generateCashFlow();

	private:

		/// Name(TYPEID, std::hash<std::string>()(symbol)) 
		/// Key[0] => "symbol"
		Name m_name;

		std::atomic<double> m_quotedPrice;

		dd::date m_tradeDate;

		std::atomic<double> m_tradePrice;

		dd::date m_processedDate;

		std::atomic<double> m_yield;

		dd::date m_maturityDate;

		std::shared_ptr<cashFlowSetType> m_cashFlow;

		std::shared_ptr<IZeroCouponBond> m_bond;

		mutable SpinLock m_lock;
	};
}


/* namespace derivative */

#endif /* _DERIVATIVE_ZEROCOUPONBONDVALUE_H_ */