/*
Copyright (c) 201, Nathan Muruganantha. All rights reserved.
*/

#define ALL_MSG	0
#define EQUITY_VANILLA_OPTION 1
#define FUTURES_VANILLA_OPTION 2
#define EQUITY__OPTION_SPREAD 3
#define FUTURES__OPTION_SPREAD 4
#define EXCHANGERATE_VANILLA_OPTION 5
#define EXCHANGERATE__OPTION_SPREAD 6
#define EQUITY_BARRIER_OPTION 7
#define EQUITY_AVERAGE_OPTION 8
#define EQUITY_MARGRABE_OPTION 9
#define EQUITY_LOOKBACK_OPTION 10
#define EQUITY_CHOOSER_OPTION 11
#define FUTURES_BARRIER_OPTION 12
#define FUTURES_AVERAGE_OPTION 13
